name: Build and SonarQube Analysis (macOS)
on:
  push:
    branches: [ main ]
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  test:
    runs-on: macos-latest  # Changed to macOS
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18  # Explicit version for consistency
      - run: npm install
      - run: npm test -- --coverage

  sonarqube:
    needs: test
    runs-on: macos-latest  # Changed to macOS
    steps:
      - uses: actions/checkout@v4
      - uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}