name: Build
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarqube:
    name: SonarQube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensures all files are fetched

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # LTS version for stability
          cache: 'npm'

      - name: Install dependencies
        run: |
          # Clean install with forced ESM support
          rm -rf node_modules package-lock.json
          npm install --force
          npm list js-yaml  # Verify installation
          ls -la node_modules/js-yaml/dist  # Check ESM file exists

      - name: Run tests with coverage
        run: |
          # Explicitly set ESM mode for Jest/Vitest
          NODE_OPTIONS="--experimental-vm-modules --no-warnings" npm test -- --coverage --runInBand
          
          # Debug: Verify test artifacts
          ls -la coverage
          [ -f coverage/lcov.info ] || echo "Coverage file missing!"

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
            -Dsonar.language=js
            -Dsonar.coverage.exclusions=**/test/**,**/mocks/**
            -Dsonar.sources=src
            -Dsonar.tests=__tests__